import {useEffect,useRef,useState} from 'react';
import * as maplibregl from 'maplibre-gl';
import workerUrl from 'maplibre-gl/dist/maplibre-gl-worker.mjs?worker&url';
import type {FeatureCollection} from 'geojson';
import 'maplibre-gl/dist/maplibre-gl.css';
import {Layers,Navigation,LocateFixed,Bus,MapPin} from 'lucide-react';
import type {Vehicle,Stop,RouteDetail,TrafficPoint,Operator} from './api';
maplibregl.setWorkerUrl(workerUrl);

type Props={vehicles:Vehicle[],stops:Stop[],operators:Operator[],route?:RouteDetail,traffic?:TrafficPoint[],bins:number[],focus?:{lat:number,lon:number},onVehicle:(v:Vehicle)=>void,onStop:(s:Stop)=>void};
function marker(color:string,estimated:boolean){const c=document.createElement('canvas');c.width=48;c.height=48;const x=c.getContext('2d')!;x.fillStyle='white';x.strokeStyle=color;x.lineWidth=3;if(estimated)x.setLineDash([4,3]);x.beginPath();x.arc(24,24,20,0,Math.PI*2);x.fill();x.stroke();x.setLineDash([]);x.fillStyle='#1e293b';x.fillRect(15,12,18,23);x.fillStyle='white';x.fillRect(18,16,12,9);x.fillStyle='#f5b800';x.fillRect(18,28,3,3);x.fillRect(27,28,3,3);x.fillStyle='#1e293b';x.fillRect(16,34,4,4);x.fillRect(28,34,4,4);return x.getImageData(0,0,48,48)}
export default function TransitMap(props:Props){const container=useRef<HTMLDivElement>(null),map=useRef<maplibregl.Map|null>(null),current=useRef(props);current.current=props;const [ready,setReady]=useState(false),[layers,setLayers]=useState(false),[showStops,setShowStops]=useState(false),[showVehicles,setShowVehicles]=useState(true),[notice,setNotice]=useState('');
 useEffect(()=>{const m=new maplibregl.Map({container:container.current!,style:'https://tiles.openfreemap.org/styles/positron',center:[-9.145,38.731],zoom:12.3,attributionControl:false});map.current=m;m.addControl(new maplibregl.AttributionControl({compact:true}),'bottom-right');m.on('load',()=>{for(const op of current.current.operators){m.addImage(op.id,marker(op.color,false));m.addImage(op.id+'-estimated',marker(op.color,true))};m.addImage('default',marker('#f5b800',false));for(const source of ['vehicles','stops','route','traffic'])m.addSource(source,{type:'geojson',data:{type:'FeatureCollection',features:[]}});m.addLayer({id:'route-line',type:'line',source:'route',paint:{'line-color':['get','color'],'line-width':5,'line-opacity':0.8}});m.addLayer({id:'stop-points',type:'circle',source:'stops',paint:{'circle-color':'#fff','circle-radius':4,'circle-stroke-color':'#f59f00','circle-stroke-width':2}});m.addLayer({id:'traffic-points',type:'circle',source:'traffic',paint:{'circle-radius':10,'circle-opacity':0.8,'circle-stroke-width':1,'circle-stroke-color':'#fff'}});m.addLayer({id:'vehicle-points',type:'symbol',source:'vehicles',layout:{'icon-image':['get','icon'],'icon-size':0.7,'icon-allow-overlap':true},paint:{'icon-opacity':['case',['get','stale'],0.4,1]}});m.on('click','vehicle-points',e=>{const id=e.features?.[0].properties?.id;const v=current.current.vehicles.find(v=>v.id===id);if(v)current.current.onVehicle(v)});m.on('click','stop-points',e=>{const id=e.features?.[0].properties?.id;const s=current.current.stops.find(s=>s.id===id);if(s)current.current.onStop(s)});for(const layer of ['vehicle-points','stop-points']){m.on('mouseenter',layer,()=>m.getCanvas().style.cursor='pointer');m.on('mouseleave',layer,()=>m.getCanvas().style.cursor='')};setReady(true)});m.on('error',()=>setNotice('Alguns elementos do mapa não estão disponíveis.'));return()=>{m.remove();map.current=null}},[]);
 useEffect(()=>{const m=map.current;if(!ready||!m)return;for(const op of props.operators){if(!m.hasImage(op.id)){m.addImage(op.id,marker(op.color,false));m.addImage(op.id+'-estimated',marker(op.color,true))}};const set=(name:string,data:unknown)=>(m.getSource(name) as maplibregl.GeoJSONSource).setData(data as FeatureCollection);set('vehicles',{type:'FeatureCollection',features:props.vehicles.map(v=>({type:'Feature',geometry:{type:'Point',coordinates:[v.lon,v.lat]},properties:{id:v.id,stale:v.stale,icon:m.hasImage(v.operator_id)?v.operator_id+(v.position_kind==='estimated'?'-estimated':''):'default'}}))});set('stops',{type:'FeatureCollection',features:props.stops.map(s=>({type:'Feature',geometry:{type:'Point',coordinates:[s.lon,s.lat]},properties:{id:s.id}}))});set('route',{type:'FeatureCollection',features:props.route?.geometry?.length?[{type:'Feature',geometry:{type:'LineString',coordinates:props.route.geometry},properties:{color:props.route.color}}]:[]});set('traffic',{type:'FeatureCollection',features:(props.traffic??[]).map(v=>({type:'Feature',geometry:{type:'Point',coordinates:[v.lon,v.lat]},properties:{speed:v.speed_kmh,id:v.id}}))});const palette=['#d32f2f','#ed6c22','#f3a600','#e6d73f','#79ba65','#2b9076','#2576ae'];const expression:maplibregl.ExpressionSpecification=['step',['get','speed'],palette[0]];props.bins.forEach((v,i)=>expression.push(v,palette[Math.min(i+1,palette.length-1)]));m.setPaintProperty('traffic-points','circle-color',expression);m.setLayoutProperty('vehicle-points','visibility',showVehicles&&!props.traffic?'visible':'none');m.setLayoutProperty('stop-points','visibility',showStops?'visible':'none');m.setLayoutProperty('traffic-points','visibility',props.traffic?'visible':'none')},[ready,props.vehicles,props.stops,props.route,props.traffic,props.operators,props.bins,showVehicles,showStops]);
 useEffect(()=>{if(props.focus)map.current?.flyTo({center:[props.focus.lon,props.focus.lat],zoom:15})},[props.focus]);
 useEffect(()=>{if(!ready||!props.route?.geometry?.length)return;const bounds=new maplibregl.LngLatBounds();props.route.geometry.forEach(c=>bounds.extend([c[0],c[1]]));map.current?.fitBounds(bounds,{padding:80,maxZoom:14,duration:700})},[props.route,ready]);
 const locate=()=>navigator.geolocation?navigator.geolocation.getCurrentPosition(p=>map.current?.flyTo({center:[p.coords.longitude,p.coords.latitude],zoom:14}),()=>setNotice('Localização não disponível. Verifique a permissão do navegador.')):setNotice('Este navegador não disponibiliza localização.');
 return <><div ref={container} className="map" aria-label="Mapa dos transportes de Lisboa"/><div className="map-controls"><button className="circle" aria-label="Camadas do mapa" onClick={()=>setLayers(!layers)}><Layers size={20}/></button>{layers&&<div className="layer-panel"><label><input type="checkbox" checked={showVehicles} onChange={e=>setShowVehicles(e.target.checked)}/><Bus size={15}/> Veículos</label><label><input type="checkbox" checked={showStops} onChange={e=>setShowStops(e.target.checked)}/><MapPin size={15}/> Paragens</label><small>Tracejado: posição estimada<br/>Transparente: observação antiga</small></div>}</div><div className="map-location"><button className="circle" aria-label="Orientar para norte" onClick={()=>map.current?.easeTo({bearing:0,pitch:0})}><Navigation size={20}/></button><button className="circle" aria-label="A minha localização" onClick={locate}><LocateFixed size={20}/></button></div>{notice&&<button className="map-notice" onClick={()=>setNotice('')}>{notice} ×</button>}</>
}
